package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

type schema struct {
	Defs map[string]json.RawMessage `json:"$defs"`
}

type def struct {
	OneOf      []ref                      `json:"oneOf"`
	Const      string                     `json:"const"`
	Enum       []string                   `json:"enum"`
	Required   []string                   `json:"required"`
	Properties map[string]json.RawMessage `json:"properties"`
}
type ref struct {
	Ref string `json:"$ref"`
}

func main() {
	if len(os.Args) != 3 {
		panic("usage: generate-contract-ts <schema> <output>")
	}
	raw, err := os.ReadFile(os.Args[1])
	if err != nil {
		panic(err)
	}
	var s schema
	if err := json.Unmarshal(raw, &s); err != nil {
		panic(err)
	}
	blockNames := []string{}
	var blockDef def
	must(json.Unmarshal(s.Defs["block"], &blockDef))
	for _, r := range blockDef.OneOf {
		blockNames = append(blockNames, strings.TrimPrefix(r.Ref, "#/$defs/"))
	}
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by scripts/generate-contract-ts.go from schemas/view-document.json; DO NOT EDIT.\n")
	fmt.Fprintf(&out, "// Source SHA256: %x\n\n", sha256.Sum256(raw))
	fmt.Fprintf(&out, "export const CANONICAL_VIEW_DOCUMENT_VERSION = \"viewdoc.flipctl.dev/v1alpha1\" as const;\n\n")
	fmt.Fprintf(&out, "export type ViewAction = {\n  id: string;\n  label: string;\n  enabled: boolean;\n  role?: \"primary\" | \"secondary\" | \"destructive\";\n  params?: Record<string, string>;\n};\n\n")
	fmt.Fprintf(&out, "export type ViewDocument = {\n  apiVersion: typeof CANONICAL_VIEW_DOCUMENT_VERSION;\n  sessionId: string;\n  viewId: string;\n  revision: number;\n  title: string;\n  actions?: ViewAction[];\n  blocks: ViewBlock[];\n};\n\n")
	for _, name := range blockNames {
		emitBlock(&out, name, s.Defs[name])
	}
	types := make([]string, len(blockNames))
	for i, n := range blockNames {
		types[i] = exportName(n)
	}
	fmt.Fprintf(&out, "export type ViewBlock =\n  | %s;\n", strings.Join(types, "\n  | "))
	if err := os.WriteFile(os.Args[2], out.Bytes(), 0644); err != nil {
		panic(err)
	}
}
func must(e error) {
	if e != nil {
		panic(e)
	}
}
func exportName(n string) string {
	return strings.TrimSuffix(strings.Title(strings.ReplaceAll(n, "_", " ")), " ")
}

func emitBlock(out *bytes.Buffer, name string, raw json.RawMessage) {
	var d def
	must(json.Unmarshal(raw, &d))
	kindRaw := d.Properties["kind"]
	var kd def
	must(json.Unmarshal(kindRaw, &kd))
	req := map[string]bool{}
	for _, r := range d.Required {
		req[r] = true
	}
	keys := []string{}
	for k := range d.Properties {
		if k != "kind" {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)
	fmt.Fprintf(out, "export type %s = {\n  kind: \"%s\";\n", exportName(name), kd.Const)
	for _, k := range keys {
		fmt.Fprintf(out, "  %s%s: %s;\n", k, opt(req[k]), tsType(k, d.Properties[k]))
	}
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)
}
func opt(required bool) string {
	if required {
		return ""
	}
	return "?"
}
func tsType(k string, raw json.RawMessage) string {
	var m map[string]any
	must(json.Unmarshal(raw, &m))
	if enum, ok := m["enum"].([]any); ok {
		parts := []string{}
		for _, v := range enum {
			parts = append(parts, fmt.Sprintf("\"%s\"", v))
		}
		return strings.Join(parts, " | ")
	}
	if ref, ok := m["$ref"].(string); ok {
		switch strings.TrimPrefix(ref, "#/$defs/") {
		case "progress":
			return "{ label: string; value?: number; max?: number; text?: string }"
		case "listItem":
			return "Array<{ label: string; value?: string; description?: string; action?: ViewAction }>"
		}
	}
	if typ, _ := m["type"].(string); typ == "array" {
		switch k {
		case "fields":
			return "Array<{\n    id: string;\n    label: string;\n    type: string;\n    default?: string;\n    required?: boolean;\n    validation?: string;\n    options?: string[];\n  }>"
		case "pairs":
			return "Array<{ key: string; value: string }>"
		case "columns":
			return "Array<{ id: string; label: string }>"
		case "rows":
			return "Array<{ cells: Record<string, string> }>"
		case "lines":
			return "Array<{ id?: string; source?: string; text: string; severity?: string }>"
		case "items":
			return "Array<{ label: string; value?: string; description?: string; action?: ViewAction }>"
		}
	}
	if typ, _ := m["type"].(string); typ == "string" {
		return "string"
	}
	return "unknown"
}
