[package]
name    = "tauri-remote"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri        = { version = "2", features = [] }
async-stream = "0.3"
axum         = { version = "0.7", features = ["ws"] }
bytes        = "1"
clap         = { version = "4", features = ["derive"] }
image        = { version = "0.25", default-features = false, features = ["jpeg"] }
serde        = { version = "1", features = ["derive"] }
tokio        = { version = "1", features = ["full"] }

[target.'cfg(target_os = "linux")'.dependencies]
cairo-rs   = "0.18"
glib       = "0.18"
gtk        = "0.18"
webkit2gtk = { version = "=2.0.2", features = ["v2_40"] }
