// Code generated by scripts/generate-contract-ts.go from schemas/view-document.json; DO NOT EDIT.
// Source SHA256: fc6021e0f3287ea68e67952747d66ad1041a3550bc2a186910c275a7e424345b

export const CANONICAL_VIEW_DOCUMENT_VERSION = "viewdoc.flipctl.dev/v1alpha1" as const;

export type ViewAction = {
  id: string;
  label: string;
  enabled: boolean;
  role?: "primary" | "secondary" | "destructive";
  params?: Record<string, string>;
};

export type ViewDocument = {
  apiVersion: typeof CANONICAL_VIEW_DOCUMENT_VERSION;
  sessionId: string;
  viewId: string;
  revision: number;
  title: string;
  actions?: ViewAction[];
  blocks: ViewBlock[];
};

export type TextBlock = {
  kind: "text";
  id: string;
  text: string;
  title?: string;
};

export type NoticeBlock = {
  kind: "notice";
  id: string;
  severity: "info" | "success" | "warning" | "error";
  text: string;
  title?: string;
};

export type ListBlock = {
  kind: "list";
  id: string;
  items: Array<{ label: string; value?: string; description?: string; action?: ViewAction }>;
  title?: string;
};

export type FormBlock = {
  kind: "form";
  fields: Array<{
    id: string;
    label: string;
    type: string;
    default?: string;
    required?: boolean;
    validation?: string;
    options?: string[];
  }>;
  id: string;
  title?: string;
};

export type KeyValueBlock = {
  kind: "key_value";
  id: string;
  pairs: Array<{ key: string; value: string }>;
  title?: string;
};

export type TableBlock = {
  kind: "table";
  columns: Array<{ id: string; label: string }>;
  id: string;
  rows: Array<{ cells: Record<string, string> }>;
  title?: string;
};

export type LogBlock = {
  kind: "log";
  id: string;
  lines: Array<{ id?: string; source?: string; text: string; severity?: string }>;
  title?: string;
};

export type ProgressBlock = {
  kind: "progress";
  id: string;
  progress: { label: string; value?: number; max?: number; text?: string };
  title?: string;
};

export type ViewBlock =
  | TextBlock
  | NoticeBlock
  | ListBlock
  | FormBlock
  | KeyValueBlock
  | TableBlock
  | LogBlock
  | ProgressBlock;
