import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

describe("generated ViewDocument public TypeScript contract", () => {
  const source = readFileSync(resolve(__dirname, "viewDocumentTypes.ts"), "utf8");

  it("is generated from the schema and does not broaden public discriminants", () => {
    expect(source).toContain(
      "Code generated by scripts/generate-contract-ts.go from schemas/view-document.json",
    );
    expect(source).toContain("apiVersion: typeof CANONICAL_VIEW_DOCUMENT_VERSION;");
    expect(source).toContain("export type ViewBlock =");
    for (const blockType of [
      "TextBlock",
      "NoticeBlock",
      "ListBlock",
      "FormBlock",
      "KeyValueBlock",
      "TableBlock",
      "LogBlock",
      "ProgressBlock",
    ]) {
      expect(source).toContain(`| ${blockType}`);
    }
    expect(source).not.toContain("| string");
  });
});
